version: "3.9"
services:
  judol-detector-be:
    image: ghcr.io/${REPOSITORY_OWNER}/judol-detector-be:latest
    container_name: judol-detector-be
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
